on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          url: ${{ secrets.URL }}
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'execute-sql'
          classpath: 'example/changelogs'
          sqlFile: 'insert_data.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          url: ${{ secrets.URL }}
