on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          url: ${{ secrets.URL }}
      - name: Execute postgress file
        run: psql -h postgres.cxvuo26fbjpa.us-east-1.rds.amazonaws.com -p 5432 -U postgres -d test_db -f example/changelogs/insert_data.sql --password=Mah696794

